title: Gabe Lynch
url: "https://gplynch.com"
baseurl: 

markdown: kramdown

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Bio"
   link: "/"
 - name: "CV"
   link: "files/cv.pdf"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
